#!/bin/sh
#voms-proxy-init --voms cms --valid 100:00

#PromptREco
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016B-03Feb2017_ver2-v2/MINIAOD SINGLEMUON2016B_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016C-03Feb2017-v1/MINIAOD SINGLEMUON2016C_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016D-03Feb2017-v1/MINIAOD SINGLEMUON2016D_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016E-03Feb2017-v1/MINIAOD SINGLEMUON2016E_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016F-03Feb2017-v1/MINIAOD SINGLEMUON2016F_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016G-03Feb2017-v1/MINIAOD SINGLEMUON2016G_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-ReReco.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016H-03Feb2017_ver2-v1/MINIAOD SINGLEMUON2016Hv2_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016H-03Feb2017_ver3-v1/MINIAOD SINGLEMUON2016Hv3_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  

farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016B-03Feb2017_ver2-v2/MINIAOD SINGLEELE2016B_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016C-03Feb2017-v1/MINIAOD SINGLEELE2016C_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016D-03Feb2017-v1/MINIAOD SINGLEELE2016D_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016E-03Feb2017-v1/MINIAOD SINGLEELE2016E_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016F-03Feb2017-v1/MINIAOD SINGLEELE2016F_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016G-03Feb2017-v1/MINIAOD SINGLEELE2016G_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-ReReco.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016H-03Feb2017_ver2-v1/MINIAOD SINGLEELE2016Hv2_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016H-03Feb2017_ver3-v1/MINIAOD SINGLEELE2016Hv3_SMHiggs_Feb23 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
