#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

#PromptREco
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016B-23Sep2016-v3/MINIAOD SINGLEMUON2016B_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016C-23Sep2016-v1/MINIAOD SINGLEMUON2016C_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016D-23Sep2016-v1/MINIAOD SINGLEMUON2016D_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016E-23Sep2016-v1/MINIAOD SINGLEMUON2016E_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016F-23Sep2016-v1/MINIAOD SINGLEMUON2016F_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016G-23Sep2016-v1/MINIAOD SINGLEMUON2016G_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-ReReco.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016H-PromptReco-v2/MINIAOD SINGLEMUON2016Hv2_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016H-PromptReco-v3/MINIAOD SINGLEMUON2016Hv3_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  

farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016B-23Sep2016-v3/MINIAODD SINGLEELE2016B_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016C-23Sep2016-v1/MINIAOD SINGLEELE2016C_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016D-23Sep2016-v1/MINIAOD SINGLEELE2016D_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016E-23Sep2016-v1/MINIAOD SINGLEELE2016E_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016F-23Sep2016-v1/MINIAOD SINGLEELE2016F_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-BCDEF.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016G-23Sep2016-v1/MINIAOD SINGLEELE2016G_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON-ReReco.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016H-PromptReco-v2/MINIAOD SINGLEELE2016Hv2_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
farmoutAnalysisJobs  $1  --assume-input-files-exist --vsize-limit=8000   --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016H-PromptReco-v3/MINIAOD SINGLEELE2016Hv3_SMHiggs_Jan30 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
